### ISSUE TITLE
EPS: Test basic solar panel function

### ISSUE THREAD

**Issue by reidcol12** [CougsInSpace/CougSat1-Hardware#1]
Test current voltage output of solar cell

**Comment by WattsUp** [comment]
Solar cells output 2.45Voc and 25mAsc under our grow light
Voltages of 2.7 have been recorded under the real sun through the window
Currents of 80mA have been recorded under the real sun through the window
Our SpectroLabs contact confirmed we will not see the rated 400mA without being in orbit or under an artifical sun with AM0 spectrum.
