### ISSUE TITLE
THERMAL- Get GrabCAD accounts and Link it to The CIS Group. Solidworks Download Optional

### ISSUE THREAD

**Issue by mvguerrero** [CougsInSpace/CougSat1-Hardware#108]
Download Solidworks and get a grabcad account. Aaron can link you to the grabcad once you make an account.  

If you don't have access to a computer which can run solidworks, let me know below as well. You can still get access to the Grabcad, and be ready once you are back at Voiland and have access to the Computer/CAD lab. 

Post your progress below, and the issue will close when everyone has an account.

**Comment by mvguerrero** [comment]
I have a linked grabcad account, but not solidworks yet. I will work on getting Solidworks.

**Comment by WattsUp** [comment]
Add this information to a formal document or just Slack not an issue

Abandoning this issue
