### ISSUE TITLE
THERMAL- Learn the basics of Aurdino assembly and programming

### ISSUE THREAD

**Issue by mvguerrero** [CougsInSpace/CougSat1-Hardware#109]
Alex has taken the task of becoming familiar with the creation of useful micro controller based gadgets.

He has bought a kit with the requisite parts and instructions to gain this capability.
Please tell me your github name so I can give you credit Alex

**Comment by WattsUp** [comment]
Not directly related to CougSat-1. Not an issue

Abandoning this issue.
