### ISSUE TITLE
THERMAL- Live Documentation Zone

### ISSUE THREAD

**Issue by mvguerrero** [CougsInSpace/CougSat1-Hardware#110]
Mario will post the current Thermal Team documentation he has created here.
Feel free to comment so I can improve it!
-Mario

**Comment by mvguerrero** [comment]
[Thermal Team Documentation V1.docx](https://github.com/CougsInSpace/CougSat1-Hardware/files/2109388/Thermal.Team.Documentation.V1.docx)

**Comment by WattsUp** [comment]
Either put documentation in the repository or the Google Drive

Closing this issue
