### ISSUE TITLE
THERMAL- Math Based Thermal Models

### ISSUE THREAD

**Issue by mvguerrero** [CougsInSpace/CougSat1-Hardware#112]
Meet with Dr. Ian Richards to create a mathematical model of the space environment, as it pertains to Cougsat 1.  Topics include:
Orbit timing
Orbit period
Beta angle 
Heat dissipation
Temperature dependency

**Comment by mvguerrero** [comment]
The scholar document for cube sat thermal analysis showed our procedure for our work:
1: Thermal calculations for cube without internal components
2: Determining orbit time and cube rotation determination
3: Beta angle defining system temperature dependency
4: Power budget and analysis with all components

Done: Found that cold dependent is a priority, and our beta angle must be less than 60deg. Still need an exact, part to part power budget
-Kevin

**Comment by WattsUp** [comment]
What is the reason for reopening this?

**Comment by mvguerrero** [comment]
Issue was reopened to add more information from the team's old drive. Instead we added the information in the resources tab. Closing issue
