### ISSUE TITLE
ENVIRONMENTAL CONTROL: Store the thermal vacuum

### ISSUE THREAD

**Issue by mvguerrero** [CougsInSpace/CougSat1-Hardware#114]
Housing indefinitely
Will need to transport it

**Comment by WattsUp** [comment]
Darin can house the T-Vac for the foreseeable future.

**Comment by mvguerrero** [comment]
Darin is housing the T-Vac at his apartment

**Comment by mvguerrero** [comment]
The oven is no longer at our disposal, Thus this issue is reopened

**Comment by mvguerrero** [comment]
I recontacted Darin, he is very busy and cannot spare much time. But he is now asking the individual who lent us the T-Vac if we can borrow it again. He will still get credit for resolving this issue.

**Comment by mvguerrero** [comment]
We already have a vacuum chamber which we can modify to suit our needs. we no longer need to seek the T-Vac
