### ISSUE TITLE
COUGSAT-1: Create System Requirements

### ISSUE THREAD

**Issue by WattsUp** [CougsInSpace/CougSat1-Hardware#117]

**Comment by WattsUp** [comment]
This also involves a SRR

**Comment by WattsUp** [comment]
Need to separate system requirements and design requirements
"The CubeSat shall have contact with the ground station at all times" vs "The RCS should be full duplex"
Must haves vs nice to haves
And design requirement should be traceable to a system requirement
System requirements are a "constitution": able to change but difficult/long process

Change CubeSat specifications to "Must comply with CubeSat Specification 3.1.1" to allow the CubeSat document to change without needing to update our document. It's okay with a small project though. Might add  a revision number that we are referencing to.

Rename priority levels: minimum requirement (non negotiable), can change the value, cosmetic, etc.
Key performance parameters
Bare minimum
Expectations
All design requirements are equal

**Comment by CodySigvartson** [comment]
[meetingnotes.docx](https://github.com/CougsInSpace/CougSat1-Hardware/files/2174283/meetingnotes.docx)

This file contains notes on requirement revisions from the SRR. If you have any questions please reach out to me
