### ISSUE TITLE
Become Proficient With Solidworks (Read Description)

### ISSUE THREAD

**Issue by colinwarn** [CougsInSpace/CougSat1-Hardware#17]
Go through ME116 and ME216.  If you've already taken these classes, disregard this task.

If you've taken ME116 but not ME216, look into vibration testing with Solidworks. Talk to either the head of structures or the professor of ME216 and they should have some resources for you to learn vibration testing.

If you've taken neither, go through the following tutorials provided by Solidworks:
http://www.solidworks.com/sw/resources/solidworks-tutorials.htm

1 - Introduction
2 - Parts
3 - Assemblies
5 - Drawings

If you still don't feel comfortable after going through these, YouTube videos on Solidworks for Beginners are quite helpful.

**Comment by WattsUp** [comment]
Add this information to a formal document not an issue

Abandoning this issue
