### ISSUE TITLE
GROUND: Fabricate Antenna Tracker and Antennas V1.0

### ISSUE THREAD

**Issue by WattsUp** [CougsInSpace/CougSat1-Hardware#217]

**Comment by colinwarn** [comment]
Finished.  Check the room for the parts.

Please award points to the following people to the following amount:

Aiden Pyle - 10 points
Makenna Mullen - 8 Points
Alyssa Hovenkotter - 8 Points

**Comment by RyanDorosh** [comment]
The individual towers were completed a while ago, I just forgot to close this issue.
