### ISSUE TITLE
STRUCT: Frontplane (+X Cover) Design (due end of July)

### ISSUE THREAD

**Issue by colinwarn** [CougsInSpace/CougSat1-Hardware#243]
Create a 1-2mm panel for the frontplane of the Cubesat that can integrate:

-Umbilical cord hole
-RBF Hole
(solar panels?)
(magnetorquer?)
(Thermal insulation?)

Attitude is responsible for their own mounting mechanism.

**Comment by WattsUp** [comment]
It will need pass through for two antenna cables. Maybe three. 
No solar panels nor magnetorquer mounting needed

**Comment by colinwarn** [comment]
[Front Plane.PDF](https://github.com/CougsInSpace/CougSat1-Hardware/files/2199541/Front.Plane.PDF)
[Front Plane.zip](https://github.com/CougsInSpace/CougSat1-Hardware/files/2199542/Front.Plane.zip)

Latest update to drawings.

**Comment by colinwarn** [comment]
[Front Plane.PDF](https://github.com/CougsInSpace/CougSat1-Hardware/files/2203537/Front.Plane.PDF)
[Front Plane.zip](https://github.com/CougsInSpace/CougSat1-Hardware/files/2203538/Front.Plane.zip)
