### ISSUE TITLE
Get Center of Mass Calculation (due end of September)

### ISSUE THREAD

**Issue by colinwarn** [CougsInSpace/CougSat1-Hardware#291]
-Make sure each component's mass estimate is within 1 gram of it's datasheet weight
-Assemble all components

Center of Mass must be within 2cm^3 of the center of CougSat-I

max volume design - Max volume for hand modeled parts. Fit check, assume worst case. Use premade CAD parts when possible.
mass: For parts 20g or larger, worry about center of mass distribution.
vibration: More than 10% the mass of the board, model it. For connection areas, get contacting surface area modeled correctly.

Unless you can tell explicitly by looking at the object where a given material is, assume uniform distribution.

**Comment by WattsUp** [comment]
3.2.14 and 3.2.14.1: within 2cm, not 2 cm³. A volume dimension here doesn't make sense. I believe this means the point can be inside of a 4cm cube centered about the geometric center and not a 4cm diameter sphere. It is kind of ambiguous
