### ISSUE TITLE
Retrospective: 1 July → 1 August

### ISSUE THREAD

**Issue by WattsUp** [CougsInSpace/CougSat1-Hardware#295]
## Points to Discuss ##
**Add comments here**
- Has every team lead started thinking about their onboarding/training processes when they get new team members? I.e. How they'll get new members up to speed on what they'll be working on? (question from Colin)

### Things to start: ###
- Review earlier both formal and peer
- Stand-ups with the whole team
- Have a game plan
- Have team leads assign assignee(s) within the deferral time period 
### Things to stop: ###
- Missing meetings without informing and making it up with the meeting coordinator
### Things to continue doing: ###
- Everything from the structure perspective seems to be moving pretty smoothly. My thoughts are to continue holding course. (comment from Colin)

**Comment by phillip-whitworth** [comment]
while I am not sure what I should be really adding to this here are my thoughts based on the very little sprint interaction I have had.

Things to start:
clearly establish what each section is getting completed or attempting to complete, some of the issues are a little too vague.

for ADCS we need to start the coding process.  need to build the basics and get the de-tumbling routine coded and start testing it.  once that goes to testing then the other fun stuff can start getting coded like roasting the chicken and ground targeting for imagery.

I need to add the coil creation to this sprint and make sure the build fits into the build without issues.   

Things to stop:
procrastination and vacations.

Things to continue doing:
Weekly updates via conference calls.  
helping other teams get their issues completed if your team doesn't have a heavy work load.  you know, if you can that is.
