### ISSUE TITLE
Safety Case for CubeSat

### ISSUE THREAD

**Issue by colinwarn** [CougsInSpace/CougSat1-Hardware#364]
Watertight case, cart for moving, small profile.

**Comment by WattsUp** [comment]
I recommend we purchase the Pelican 1300 with anti-static foam. (This is already on the equipment wishlist, might need to remind Matt). The foam will probably be cut out by us to ensure a nice fit

**Comment by colinwarn** [comment]
Pelican case ordered: https://www.casesbypelican.net/mobile/product.aspx?ProductCode=APP-1300A-Static
