### ISSUE TITLE
Design Mount for testing PCBs on the Vibe Table

### ISSUE THREAD

**Issue by GregWallace24** [CougsInSpace/CougSat1-Hardware#385]
[CougSatModuleStandard.2.1.1.pdf](https://github.com/CougsInSpace/CougSat1-Hardware/files/2523313/CougSatModuleStandard.2.1.1.pdf)

Design an adjustable mount for testing PCBs on the vibe table.  Should mount directly to the vibe-table-plate that Ryan made and should be adjustable between the old boards and the new boards.  Shall include holes for bolting in a basic backplane.

**Comment by colinwarn** [comment]
CAD here: https://workbench.grabcad.com/workbench/projects/gcZyVL8e3jBFst25EMOCFOSOSSCCtw5Og6qSO3SCIElLVA#/folder/5513523
