### ISSUE TITLE
Read Through Cubesat Crash Course Links (Read Description)

### ISSUE THREAD

**Issue by colinwarn** [CougsInSpace/CougSat1-Hardware#4]
Cubesat Crash Course:
[https://www.evernote.com/shard/s366/sh/db200dbf-da8f-46a1-9456-a1ef92f1601e/340e40ced7bf6999d512c62bae0b8cbc](url)

**Comment by WattsUp** [comment]
Add this information to a formal document not an issue

Abandoning this issue
