### ISSUE TITLE
ENVIRONMENTAL CONTROL-Research Resistor Circuit for the Vacuum Chamber

### ISSUE THREAD

**Issue by wilmothalex** [CougsInSpace/CougSat1-Hardware#404]
The goal of this issue is to research possible designs for creating a circuit which radiates the desired amount of heat onto a satellite model within a vacuum chamber.

**Comment by mvguerrero** [comment]
[Circuit Analysis for Vacuum Chamber Heat Transfer.docx](https://github.com/CougsInSpace/CougSat1-Hardware/files/2583239/Circuit.Analysis.for.Vacuum.Chamber.Heat.Transfer.docx)

Here's the document which  the participants created!
