### ISSUE TITLE
ADCS - Wrap Test Coil

### ISSUE THREAD

**Issue by phillip-whitworth** [CougsInSpace/CougSat1-Hardware#405]
Wrap the first coil to specs

**Comment by phillip-whitworth** [comment]
We wrapped one of these and found some issues with the procedure. I think we have finished this issue but we will have other coils needing to be wrapped.

**Comment by phillip-whitworth** [comment]
Need to Add Jack Price to this as well.

**Comment by quintonclum-123** [comment]
![test coil 1](https://user-images.githubusercontent.com/43120432/52385780-feeca400-2a37-11e9-8ee1-41c65daf9883.jpg)

Image of a wrapped Test Coil inside its wrapping device!
