### ISSUE TITLE
EPS: Fabricate Battery Heatsink V1.0

### ISSUE THREAD

**Issue by WattsUp** [CougsInSpace/CougSat1-Hardware#424]
CAD:
https://workbench.grabcad.com/workbench/projects/gcZyVL8e3jBFst25EMOCFOSOSSCCtw5Og6qSO3SCIElLVA#/file/425014161

We will need at least 2 of the one labelled EPS_BatteryHeatsink.stp for our actual board and then one of the design like EPS_BatteryHeatsink(1).STL. The one that wraps around the entire battery we will want to be around 65 mm in length and as thin as possible for heat transfer purposes.

**Comment by colinwarn** [comment]
ProShop is currently machining this part.

**Comment by colinwarn** [comment]
Part has been machined.
