### ISSUE TITLE
Test/Verify Battery Protection Circuit on Powerboard (due May 13th)

### ISSUE THREAD

**Issue by reidcol12** [CougsInSpace/CougSat1-Hardware#53]
Verify that the battery protection IC on the powerboard does protect the battery for the expected conditions.

**Comment by WattsUp** [comment]
Over voltage protection: PASS 4.25V
Under voltage protection: PASS 2.8V
Short circuit protection: PASS, re-enables after charger (solar) is on
Over current protection: Probably PASS, cannot test without large load resistors but SCP works and they use the same mechanism
