### ISSUE TITLE
ENVIRONMENTAL CONTROL- Prototype Cooling Chamber Components.

### ISSUE THREAD

**Issue by mvguerrero** [CougsInSpace/CougSat1-Hardware#556]
Use Dry Ice and metal wires to conduct a study about how well metal wires can remove heat from a closed system. This method is currently the main way to remove heat from a system for testing purposes, and its efficacy should be tested in the real world. 

The current conduction candidates are copper and aluminum. Copper has greater conductance than aluminum, but aluminum is much less expensive.

**Comment by pteridophobia** [comment]
We may need to wrap the exposed copper with an insulator to allow the other cool to cool

**Comment by mvguerrero** [comment]
The experiment informed us that aluminum would not be the ideal heat conductor for the chamber, and that coiling copper wire could work to remove heat from a system. We will have to source a medium diameter copper wire compatible with our planned system. Additional research should be done to find the exact diameter.
![Image from iOS](https://user-images.githubusercontent.com/38301484/67642078-6946bc80-f8c5-11e9-88e5-ba503ea280f8.jpg)
