### ISSUE TITLE
Laser Cut Low Outgassing Plastic Cutout For Satellite

### ISSUE THREAD

**Issue by colinwarn** [CougsInSpace/CougSat1-Hardware#590]
Find a low outgassing material that can be preferable cutout by a laser cutter. If you can't, no worries we'll just CNC mill it. 

CubeSat Design Specification, Page 8, 3.1.8.1 and 3.1.8.2 have the "low outgassing" definitions:
https://www.cubesat.org/resources

You'll find this link helpful for looking up materials:
https://outgassing.nasa.gov/

Cutout should be 0.5mm thick. It need to takeup the full red area as seen in this picture. Holes slightly larger than the ones within it's box must be cut so that the components can continue to stick through:
![Capture](https://user-images.githubusercontent.com/24682398/78412737-58fbe180-75c9-11ea-8748-c45119290212.JPG)

**Comment by gregstolte** [comment]
Material is Lexan polycarbonate sheet

[STR_px_Plastic_Cover.zip](https://github.com/CougsInSpace/CougSat1-Hardware/files/4441114/STR_px_Plastic_Cover.zip)

**Comment by colinwarn** [comment]
https://workbench.grabcad.com/workbench/projects/gcZyVL8e3jBFst25EMOCFOSOSSCCtw5Og6qSO3SCIElLVA#/file/524239832
