### ISSUE TITLE
THERMAL - Thermal Simulation Contraption (due end of July)

### ISSUE THREAD

**Issue by colinwarn** [CougsInSpace/CougSat1-Hardware#93]
Create a contraption that roughly simulates the thermal environment our Cubesat will be in:  Allowing us to  test the payload's environmental control system.

**Comment by mvguerrero** [comment]
Looks like we will get the chance to use a real metal model in this case. Greg commented that the rates would be the same, but the internal temperatures may differ since it's a simpler model.
